Core-Additions:
  InvisibleItemFrames: true
  CustomDeathMessages: true
  ChunkCheck: false # not yet working!
  Death-message-mob: <victim> died to a <killer>
  Death-message-player: <victim> died to <killer>
